USE_CAMERA_STUB := false
BOARD_USES_ECLAIR_LIBCAMERA := true

TARGET_BOARD_PLATFORM := msm7k
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_CPU_ABI := armeabi
TARGET_CPU_ABI2 := armeabi-v6l
TARGET_BOOTLOADER_BOARD_NAME := swift

#TARGET_ARCH_VARIANT := armv5te-vfp
#TARGET_GLOBAL_CFLAGS += -mfpu=vfp -mfloat-abi=softfp
#TARGET_GLOBAL_CPPFLAGS += -mfpu=vfp -mfloat-abi=softfp
ARCH_ARM_HAVE_VFP := true


TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true
TARGET_NO_RADIOIMAGE := true

#BOARD_USES_GENERIC_AUDIO := true

#BOARD_USES_ECLAIR_LIBAUDIO := true

TARGET_PROVIDES_LIBAUDIO := true
#BOARD_USES_ALSA_AUDIO := true
#BUILD_WITH_ALSA_UTILS := true

BOARD_USE_HTC_LIBSENSORS := false
TARGET_PROVIDES_LIBRIL := true
NEW_LIBRIL_HTC := true
TARGET_PROVIDES_INIT_TARGET_RC := true
TARGET_USES_OLD_LIBSENSORS_HAL := true
TARGET_OTA_ASSERT_DEVICE := swift

BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true

BOARD_EGL_CFG := device/lg/swift/files/egl.cfg

BOARD_GPS_LIBRARIES := libloc_api
BOARD_USES_GPSSHIM := true
BOARD_GPS_NEEDS_XTRA := true
#BOARD_GPS_BAD_AGPS := true
#BOARD_GPS_LIBRARIES := libloc

BOARD_VENDOR_USE_AKMD := akm8973

### enable bluetouth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BRCM_BT_USE_BTL_IF := false
BT_ALT_STACK := false
#BT_USE_BTL_IF := false
BRCM_BTL_INCLUDE_A2DP := true
BRCM_BTL_INCLUDE_OBEX := true
BRCM_BTL_OBEX_USE_DBUS := true

### enable FM radio
BOARD_HAVE_FM_RADIO := true
BOARD_USE_BROADCOM_FM_VOLUME_HACK := true
BOARD_FM_DEVICE := bcm4325
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

### enable wifi
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
WPA_SUPPLICANT_VERSION := VER_0_5_X
BOARD_WLAN_DEVICE := bcm4325
BOARD_SOFTAP_DEVICE := bcm4325
#BOARD_WIRELESS_CHIP := bcm4325
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/etc/wl/rtecdc.bin nvram_path=/system/etc/wl/nvram.txt"
WIFI_DRIVER_MODULE_NAME := wireless
WIFI_DRIVER_FW_STA_PATH := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_AP_PATH := "/system/etc/wl/rtecdc-apsta.bin"
WIFI_DRIVER_HAS_LGE_SOFTAP := true




###Optimization 
ENABLE_WTF_USE_ACCELERATED_COMPOSITING := true
WITH_A2DP := true
#TINY_TOOLBOX :=true
#TARGET_HAVE_TSLIB := true
#TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

#Sensors
BOARD_VENDOR_USE_AKMD := true
TARGET_USES_OLD_LIBSENSORS_HAL := true
BOARD_VENDOR_USE_AKMD := akm8973
TARGET_SENSORS_NO_OPEN_CHECK := true
TARGET_WANTS_OLD_ACTIVATE_BEHAVIOR := true

BOARD_USE_USB_MASS_STORAGE_SWITCH := true
#BOARD_CUSTOM_USB_CONTROLLER := ../../device/lge/swift/netd/UsbController.cpp
#TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/msm_hsusb/gadget/lun"
#BOARD_UMS_LUNFILE := /sys/devices/platform/msm_hsusb/gadget/lun0/file

#WITH_DEXPREOPT := true

WITH_JIT := true
ENABLE_JSC_JIT := true
#JS_ENGINE := v8

TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true

# Use RGB565 surfaces until userspace drivers are upgraded
BOARD_NO_RGBX_8888 := true

BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true

TARGET_DO_NOT_SETS_CAN_DRAW := true

#bionic: Add NASTY_PTHREAD_CREATE_HACK
#This is a workaround for bad linkage of proprietary libs on certain devices.
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true

#BUILD_WITHOUT_PV := true
#BUILD_PV_2WAY := 1
#BUILD_PV_TEST_APPS := 1
BUILD_PV_VIDEO_ENCODERS := 1
BUILD_PV_VIDEO_ENCODERS :=true
USE_PV_WINDOWS_MEDIA := false
#BUILD_WITH_FULL_STAGEFRIGHT := true

BOARD_KERNEL_CMDLINE :=  mem=214M console=ttyMSM2,115200n8 androidboot.hardware=swift # uart.mode=arm11_uart_disable crash=off
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 0x00000800

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0f500000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x08a80000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/lg/swift/prebuilt/kernel/zImage

KERNEL_MODULES_DIR := /system/lib/modules

BOARD_GLOBAL_CFLAGS += -DCHARGERMODE_CMDLINE_NAME='"lge.reboot"' -DCHARGERMODE_CMDLINE_VALUE='"pwroff"'
